services:
  # 1. The .NET API Backend
  - type: web
    name: quantity-measurement-api
    runtime: docker
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ConnectionStrings__DefaultConnection
        fromDatabase:
          name: quantity-db
          property: connectionString
    rootDir: UC18

  # 2. The Angular Frontend
  - type: web
    name: quantity-measurement-ui
    runtime: static
    buildCommand: npm install && npm run build
    publishPath: dist/quantity-measurement-ui/browser
    rootDir: UC20/FRONTEND
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

databases:
  - name: quantity-db
    plan: free
    region: oregon
