services:
  - type: web
    name: quantity-measurement-api
    runtime: docker
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ConnectionStrings__DefaultConnection
        fromDatabase:
          name: quantity-db
          property: connectionString

databases:
  - name: quantity-db
    plan: free
    region: oregon
