// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuantityMeasurementAppRepository.Data;

#nullable disable

namespace QuantityMeasurementAppRepository.Migrations
{
    [DbContext(typeof(QuantityMeasurementDbContext))]
    [Migration("20260328070205_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuantityMeasurementAppEntity.Entity.QuantityEntity", b =>
                {
                    b.Property<string>("OperationId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("operation_id");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)")
                        .HasColumnName("error_message");

                    b.Property<bool>("IsError")
                        .HasColumnType("bit")
                        .HasColumnName("is_error");

                    b.Property<string>("Operand1Measurement")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("operand1_measurement");

                    b.Property<string>("Operand1Unit")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("operand1_unit");

                    b.Property<double>("Operand1Value")
                        .HasColumnType("float")
                        .HasColumnName("operand1_value");

                    b.Property<string>("Operand2Measurement")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("operand2_measurement");

                    b.Property<string>("Operand2Unit")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("operand2_unit");

                    b.Property<double?>("Operand2Value")
                        .HasColumnType("float")
                        .HasColumnName("operand2_value");

                    b.Property<string>("OperationType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("operation_type");

                    b.Property<string>("ResultMeasurement")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("result_measurement");

                    b.Property<string>("ResultUnit")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("result_unit");

                    b.Property<string>("ResultValue")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("result_value");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2")
                        .HasColumnName("timestamp");

                    b.HasKey("OperationId");

                    b.ToTable("quantity_measurements", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
