# Fallback config — appsettings.json takes priority

# LocalDB (default)
db.url=Server = DESKTOP-EV2BVPS\\SQLEXPRESS;Database=QuantityMeasurementDB;Trusted_Connection=True;TrustServerCertificate=True;

# SQL Server Express (uncomment to switch)
# db.url=Server=.\SQLEXPRESS;Database=QuantityMeasurementDB;Trusted_Connection=True;TrustServerCertificate=True;

db.pool.size=5
repository.type=database
db.schema.auto=false